**pandas** is a Python package to wrangle and analyze **tabular data**. Tabular data is data organized into rows and columns, basically like a spreadsheet or a table.

In [1]:
import pandas as pd
import numpy as np

A **series** is a one-dimensional array of indexed data. A `pandas.Series` has an index and a `NumPy array` does not have an index.

In [2]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[ 0.68025508  0.02565821 -0.29396287 -1.70614153]

<class 'pandas.core.series.Series'>
0    0.680255
1    0.025658
2   -0.293963
3   -1.706142
dtype: float64

In [4]:
# A series from a numpy array 
pd.Series(np.arange(3), index=[2023, 2024, 2025])
# For this method, we needed to pass a NumPy array (or a list of objects that can be converted to NumPy types) as data

2023    0
2024    1
2025    2
dtype: int64

In [5]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [6]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [7]:
# Creating a pandas.Series from a single value
# If we only provide a single number, boolean, or string as the data for the series we need to provide an index. The value will be repeated to match the length of the index. 
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

Arithmetic operations work on series and so do most NumPy functions.

In [9]:
# Define a series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [10]:
# We can also produce new pandas.Series with True/False values indicating whether the elements in a series satisfy a condition or not. 
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [11]:
# Series with NAs in it
# In pandas we can represent a missing, NULL, or NA value with the float value numpy.nan, which stands for "not a number". 
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [12]:
# Check if series has NAs
# The hasnans attribute for a pandas.Series returns True if there are any NA values in it and False otherwise.
s.hasnans

True

In [ ]:
# The isna attribute lets us see which elements in the series are NAs.
s.isna()
# The output is a pandas.Series of boolean values indicating if an element in the row at the given index is np.nan (True=is NA) or not (False=not NA)

Check-in 1: 
The integer number -999 is often used to represent missing values. Create a pandas.Series named s with four integer values, two of which are -999. The index of this series should be the letters A through D.

In [14]:
s = pd.Series(data=[100, -999, -999, 50], index=['A', 'B', 'C', 'D'])
s
# NOTE: for the index, the letters need to be in quotes because letters without quotes are treated as variable names, whereas letters inside quotes are treated as text (strings)

A    100
B   -999
C   -999
D     50
dtype: int64

Check-in 2:
In the pandas.Series documentation, look for the method mask(). Use this method to update the series s so that the -999 values are replaced by NA values. HINT: check the first example in the method’s documentation.

In [16]:
s.mask(s==-999)
# mask() replaces values wherever a condition is True. This method is saying "find the values that meet this condition and hide/replace them"

A    100.0
B      NaN
C      NaN
D     50.0
dtype: float64

**DATA FRAMES**
The pandas.DataFrame represents tabular data and we can think of it as a spreadsheet. Each column of a pandas.DataFrame is a pandas.Series (it is a dictionary of pandas.Series, with each column name being the key and the column values being the key's value)

In [17]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [18]:
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

Check-in 3:
We can access the data frame’s column names via the columns attribute. Update the column names to C1 and C2 by updating this attribute.

In [21]:
df.columns

Index(['C1', 'C2'], dtype='object')

In [22]:
df.columns = ['C1', 'C2']
df
# Setting df.columns equal to our new values assigns a new list of column names to df.columns.

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3