# Lesson 12: CSV to `geoDataFrame` + Streamline your code

Before class, make sure you can import the data we will use in [lesson 12](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-11-csv-to-geodataframe/lesson-11-csv-to-geo.html). Run the three code cells in this notebook. If they all run without errors, you are ready for class!

By the end of lesson 12, you will be able to:

- create a `geopandas.GeoDataFrame` from a CSV with longitude and latitude columns
- format printed output using f-strings
- use `for` loops, alone and with `zip()`, to avoid repeating code
- check that your code does what you expect using `assert`
- create figures with multiple axes
- write functions with docstrings to reuse code

## About the data

We will use two datasets:

1. **Power plants**: a CSV with the operable electric generating plants in the United States by energy source, as of February 2025, from the U.S. Energy Information Administration (EIA). We will read it directly from its URL, so you don't need to download it. See the [dataset's page and metadata](https://hub.arcgis.com/datasets/fedmaps::power-plants-in-the-u-s--2/about).

2. **US states**: the 2026 TIGER shapefile of the US states from the United States Census Bureau. See the [TIGER/Line shapefiles page](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2026.html) and the [technical documentation](https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2026/TGRSHP2026_TechDoc.pdf) for the metadata. To download it:
    1. At the [2026 TIGER page](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2026.html), under Download, click on "Web Interface".
    2. For year, select 2026, and for layer type select "States (and equivalent)". Click submit.
    3. Click on "Download national file".
    4. Unzip the file and move the `tl_2026_us_state` folder into a `data/` folder at the same level as this notebook.

Read the information about both datasets in the [lesson](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-11-csv-to-geodataframe/lesson-11-csv-to-geo.html) before class.

## Import libraries

In [19]:
import os

from pandas.api.types import is_string_dtype, is_numeric_dtype

import pandas as pd
import geopandas as gpd

# Display all columns when looking at dataframes
pd.set_option('display.max_columns', None)

## Import power plants data

In [2]:
URL = 'https://raw.githubusercontent.com/carmengg/eds-220-book/refs/heads/main/data/power_plants_epsg4269.csv'
power_plants = pd.read_csv(URL)

power_plants.head(3)

,objectid,plant_code,plant_name,utility_id,utility_name,sector_name,street_address,city,county,state,zip,primsource,source_desc,tech_desc,install_mw,total_mw,bat_mw,bio_mw,coal_mw,geo_mw,hydro_mw,hydrops_mw,ng_mw,nuclear_mw,crude_mw,solar_mw,wind_mw,other_mw,source,period,longitude,latitude
0,62897,1873,Tower,20910,Wolverine Power Supply Coop,Electric Utility,9663 Cooperative Road,Tower,Cheboygan,Michigan,49792,petroleum,Petroleum = 19.3 MW,Petroleum Liquids,21.3,19.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.3,0.0,0.0,0.0,"EIA-860, EIA-860M and EIA-923",202502,-84.294970,45.362818
1,62898,1874,Caro,18895,Thumb Electric Coop of Mich,Electric Utility,2437 East Dayton Road,Caro,Tuscola,Michigan,48723,petroleum,Petroleum = 8.5 MW,Petroleum Liquids,9.4,8.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.5,0.0,0.0,0.0,"EIA-860, EIA-860M and EIA-923",202502,-83.327806,43.465899
2,62899,1875,Ubly,18895,Thumb Electric Coop of Mich,Electric Utility,4159 Ubly Road,Ubly,Huron,Michigan,48475,petroleum,Petroleum = 12.3 MW,Petroleum Liquids,12.4,12.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.3,0.0,0.0,0.0,"EIA-860, EIA-860M and EIA-923",202502,-82.938806,43.721699

## Import US states shapefile

In [3]:
fp = os.path.join('/home/sarahhinkley/MEDS/eds220/eds220-inclass/week5/', 'data', 'tl_2026_us_state.shp')

states = gpd.read_file(fp)

states.head(3)

ERROR 1: PROJ: proj_create_from_database: Open of /opt/miniforge3/envs/eds220-v2/share/proj failed

,REGION,DIVISION,STATEFP,STATENS,GEOID,GEOIDFQ,STUSPS,NAME,LSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,1,2,36,01779796,36,0400000US36,NY,New York,00,G4000,A,122049230845,19256680224,+42.9133974,-075.5962723,"MULTIPOLYGON (((-74.04075 40.70017, -74.04073 ..."
1,4,8,32,01779793,32,0400000US32,NV,Nevada,00,G4000,A,284537080522,1839846018,+39.3310928,-116.6151469,"POLYGON ((-119.32418 41.99392, -119.32362 41.9..."
2,4,9,02,01785533,02,0400000US02,AK,Alaska,00,G4000,A,1479942808337,244276695297,+63.3469818,-152.8385657,"MULTIPOLYGON (((-167.55823 60.22436, -167.5567..."

## Create geodataframe from CSV

Known from metadata: the CRS of the power plants data has the code EPSG:4269

In [ ]:
# Create points from latitude and longitude
points = gpd.points_from_xy(power_plants['longitude'],
                            power_plants['latitude'])

# Create geodataframe
power_plants = gpd.GeoDataFrame(power_plants, # Data
                               geometry = points, 
                               crs = 'EPSG:4269')

In [ ]:
power_plants.geometry

In [ ]:
power_plants.plot()

## f-string

In [ ]:
print('CRS', power_plants.crs)

In [ ]:
# Explore CRS
print(f"ellipsoid: {power_plants.crs.ellipsoid}")

In [ ]:
# Any expression can go inside the curly brackets
print(f"The data has {len(power_plants):,} power plants")

print(f"Average installed capacity {power_plants['install_mw'].mean():.2f} MW")

## for loops

In [ ]:
print(states.crs)
states.plot()

In [ ]:
states.head(3)

In [6]:
# Simplify column names
states.columns = states.columns.str.lower()
states.columns

Index(['region', 'division', 'statefp', 'statens', 'geoid', 'geoidfq',
       'stusps', 'name', 'lsad', 'mtfcc', 'funcstat', 'aland', 'awater',
       'intptlat', 'intptlon', 'geometry'],
      dtype='object')

In [17]:
states.columns

Index(['region', 'division', 'statefp', 'statens', 'geoid', 'geoidfq',
       'stusps', 'name', 'lsad', 'mtfcc', 'funcstat', 'aland', 'awater',
       'intptlat', 'intptlon', 'geometry'],
      dtype='object')

In [22]:
is_string_dtype(states['region']) # says yes or no that the column is all strings

False

In [ ]:
print(states['region'].dtype)

In [7]:
# Another way of calling the function
pd.api.types.is_string_dtype(states['region']) # went into pandas and into a sub-package (api) and into another sub-package(types)

True

In [ ]:
# Check data type of codes columns
# Another way of checking, using an f string

print(f"region is string dtype? {is_string_dtype(states['region'])}")
print(f"statefp is string dtype? {is_string_dtype(states['statefp'])}")
print(f"division is string dtype? {is_string_dtype(states['division'])}")

In [20]:
# code_cols is a variable that contains a list of column names
code_cols = ['region', 'statefp', 'division']


# Check whether code columns are strings
for cols in code_cols: # for iterator in variable (or in this case, for column in list of columns)
    print(f"{cols} is string type? {is_string_dtype(states[cols])}") 
    # cols returns the name of the column being indexed
    # is_string_dtype(states[cols]) returns whether the data type for that column in the index is a string

region is string type? True
statefp is string type? True
division is string type? True

## `assert`

We want to update the data type of the columns from strings to integers. And we want to check it worked without printing things.

In [21]:
# Update the code columns into integers
for cols in code_cols:
    states[cols] = states[cols].astype('int')
    assert is_numeric_dtype(states[cols]) # assert is in the for loop so it iterates through all values in the index 
# if the assertion didn't generate any errors, that means the update worked for all columns in code_cols

How does `assert` work?

In [ ]:
2+2 == 4

In [ ]:
# Does nothing if the statement is True
assert 2+2 == 4

In [ ]:
2+2 == 3

In [ ]:
# Stops code from running if the statement is False
assert 2+2 == 3

In [14]:
# How you could add multiple asserts in one call
assert (2+2==4) & (1+1==2)

In [15]:
# Multiple asserts in one cell
assert 2+2==4
assert 1+1==2